[language-server.tsgo]
command = "tsgo"
args = ["--lsp", "-stdio"]

[language-server.oxc]
command = "oxc_language_server"

[language-server.oxc.config]
run = "onType"
typeAware = true

[language-server.oxc.config.fmt]
experimental = true

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "tsgo", except-features = ["format"] },
  { name = "oxc", only-features = ["diagnostics", "code-action", "format"] },
]
